/*
 * Generates the design-system stylesheet source, then compiles it with Tailwind.
 *
 * Two things have to be true of the CSS that ships to claude.ai/design, and
 * neither is true of the app's own compiled stylesheet:
 *
 *   1. The Avyo palette has to be the default. In app.css the real palette
 *      lives on `.product-shell` — a class applied exactly once, on the
 *      signed-in layout — while `:root` keeps the stock shadcn neutrals so the
 *      auth screens and emails can make their own contrast decisions. A design
 *      system whose components render grey unless you remember a wrapper class
 *      is a design system that renders grey. So we promote the product-shell
 *      declarations to `:root`.
 *
 *      We *copy* them at build time rather than restating them, because a
 *      hand-written second copy of thirty-five colour tokens is a copy that
 *      goes stale the first time someone retunes the palette and nothing
 *      anywhere fails.
 *
 *   2. The utility vocabulary has to exist before the markup does — see
 *      safelist.css.
 *
 * Output lands in `app/resources/css/.ds-compiled.css` rather than somewhere
 * tidier because the `@font-face` rules in fonts.css point at
 * `../fonts/instrument-sans/*.woff2`; compiled anywhere else, those relative
 * URLs stop resolving and the bundle ships without its brand font.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..');
const CSS_DIR = join(REPO, 'app', 'resources', 'css');
const APP_CSS = join(CSS_DIR, 'app.css');
const SOURCE = join(CSS_DIR, '.ds-source.css');
const OUT = join(CSS_DIR, '.ds-compiled.css');
const PREVIEWS = join(HERE, 'previews');

/** Body of a top-level rule, matched by its exact selector text. */
function ruleBody(css, selector) {
    const at = css.indexOf(`\n    ${selector} {`);
    if (at === -1) throw new Error(`build-css: selector "${selector}" not found in app.css`);
    const open = css.indexOf('{', at);
    const close = css.indexOf('}', open);
    if (close === -1) throw new Error(`build-css: unterminated rule for "${selector}"`);
    return css
        .slice(open + 1, close)
        .split('\n')
        .map((l) => l.replace(/^ {8}/, '    '))
        .join('\n')
        .replace(/^\n+|\n+$/g, '');
}

/*
 * Declarations that must NOT be promoted to :root.
 *
 * `--radius` is the one. The @theme block derives the radius scale from it —
 * `--radius-md: calc(var(--radius) - 2px)` and friends — and a custom property
 * is substituted where it is *declared*, not where it is used. Those `calc()`s
 * therefore resolve once, at :root, against the stock `--radius: 0.75rem`;
 * `.product-shell` raising it to 1rem never reaches them, so the app's real
 * scale is 8/10/12px and no component ever sees the rounder corners the
 * override was reaching for.
 *
 * Promote it here and the scale silently becomes 12/14/16px — every card,
 * input and button in the design system 4px rounder than the product. No ui/
 * component reads `var(--radius)` directly, so dropping this one declaration
 * costs nothing and keeps the two identical.
 */
const NO_PROMOTE = new Set(['--radius']);

const dropUnpromotable = (body) =>
    body
        .split('\n')
        .filter((line) => {
            const name = /^\s*(--[\w-]+)\s*:/.exec(line)?.[1];
            return !name || !NO_PROMOTE.has(name);
        })
        .join('\n');

const appCss = readFileSync(APP_CSS, 'utf8');
const light = dropUnpromotable(ruleBody(appCss, '.product-shell'));
const dark = dropUnpromotable(ruleBody(appCss, '.dark .product-shell'));
const button = ruleBody(appCss, ".product-shell [data-slot='button']");

// Tailwind errors on a @source path that does not exist.
if (!existsSync(PREVIEWS)) mkdirSync(PREVIEWS, { recursive: true });

const safelist = readFileSync(join(HERE, 'safelist.css'), 'utf8');

const tokenCount = (light.match(/^\s*--/gm) ?? []).length;

writeFileSync(
    SOURCE,
    `/*
 * GENERATED by .design-sync/build-css.mjs — do not edit, do not commit.
 * Regenerate with: node .design-sync/build-css.mjs
 */

@import './app.css';

/* The preview cards are authored outside the app's own source tree, so
   Tailwind would not otherwise see the classes they use. */
@source '${PREVIEWS}';

${safelist}

/* ──────────────────────────────────────────────────────────────────────────
 * Product palette promoted to the document root.
 *
 * Copied verbatim from \`.product-shell\` in app.css (${tokenCount} declarations).
 * Unlayered and later in source order, so it wins over both the stock \`:root\`
 * block and the layered \`.product-shell\` rule it came from.
 */
:root {
${light}
}

.dark {
${dark}
}

/*
 * The button rule keeps its layer.
 *
 * \`:root\` and \`.dark\` above are unlayered because that is where app.css puts
 * them. This one is different: its source lives in \`@layer components\`, and in
 * Tailwind's layer order utilities beat components — which is why a Button
 * carrying \`rounded-md\` renders at 10px in the real app and the pill rule never
 * actually applies. Promoting it unlayered would invert that, making every
 * button a pill that no radius utility could override, and the design system
 * would render buttons the product does not have.
 */
@layer components {
    [data-slot='button'] {
${button}
    }
}
`,
    'utf8',
);

console.error(`» wrote ${SOURCE} (${tokenCount} promoted tokens)`);

/*
 * Find a Tailwind CLI.
 *
 * The obvious place is `.ds-sync/node_modules`, where the sync run installs its
 * converter dependencies — but `.ds-sync/` is gitignored, so on a fresh clone
 * it does not exist and hardcoding that path fails with a bare ENOENT before
 * anything is written. The app does not help either: Tailwind v4 splits the CLI
 * out of the `tailwindcss` package into `@tailwindcss/cli`, and the app only
 * depends on `@tailwindcss/vite`.
 *
 * So: prefer a local install if one is there, otherwise let npx fetch the CLI
 * pinned to whatever Tailwind version the app itself resolves — matching
 * versions matters, since `@source inline(...)` needs >= 4.1.
 */
function tailwindCli() {
    for (const dir of ['.ds-sync', 'app']) {
        const bin = join(REPO, dir, 'node_modules', '.bin', 'tailwindcss');
        if (existsSync(bin)) return { cmd: bin, args: [] };
    }

    let version = 'latest';
    try {
        const pkg = join(APP, 'node_modules', 'tailwindcss', 'package.json');
        version = JSON.parse(readFileSync(pkg, 'utf8')).version || 'latest';
    } catch {
        throw new Error(
            'build-css: no Tailwind CLI and no app/node_modules/tailwindcss to read a version from.\n' +
                "  Run the app's install first (cd app && npm ci), then re-run this script.",
        );
    }

    console.error(`» no local Tailwind CLI — falling back to npx @tailwindcss/cli@${version}`);
    return { cmd: 'npx', args: ['--yes', `@tailwindcss/cli@${version}`] };
}

const { cmd, args } = tailwindCli();
execFileSync(cmd, [...args, '-i', SOURCE, '-o', OUT, '--cwd', join(REPO, 'app')], {
    stdio: 'inherit',
});

const bytes = readFileSync(OUT).length;
console.error(`» wrote ${OUT} (${(bytes / 1024).toFixed(0)} KB)`);
