/*
 * Generates the design-system stylesheet source, then compiles it with Tailwind.
 *
 * Two things have to be true of the CSS that ships to claude.ai/design, and
 * neither is true of the app's own compiled stylesheet:
 *
 *   1. The Avyo palette has to be the default. In app.css the real palette
 *      lives on `.product-shell` — a class applied exactly once, on the
 *      signed-in layout — while `:root` keeps the stock shadcn neutrals so the
 *      auth screens and emails can make their own contrast decisions. A design
 *      system whose components render grey unless you remember a wrapper class
 *      is a design system that renders grey. So we promote the product-shell
 *      declarations to `:root`.
 *
 *      We *copy* them at build time rather than restating them, because a
 *      hand-written second copy of thirty-five colour tokens is a copy that
 *      goes stale the first time someone retunes the palette and nothing
 *      anywhere fails.
 *
 *   2. The utility vocabulary has to exist before the markup does — see
 *      safelist.css.
 *
 * Output lands in `app/resources/css/.ds-compiled.css` rather than somewhere
 * tidier because the `@font-face` rules in fonts.css point at
 * `../fonts/instrument-sans/*.woff2`; compiled anywhere else, those relative
 * URLs stop resolving and the bundle ships without its brand font.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..');
const CSS_DIR = join(REPO, 'app', 'resources', 'css');
const APP_CSS = join(CSS_DIR, 'app.css');
const SOURCE = join(CSS_DIR, '.ds-source.css');
const OUT = join(CSS_DIR, '.ds-compiled.css');
const PREVIEWS = join(HERE, 'previews');

/** Body of a top-level rule, matched by its exact selector text. */
function ruleBody(css, selector) {
    const at = css.indexOf(`\n    ${selector} {`);
    if (at === -1) throw new Error(`build-css: selector "${selector}" not found in app.css`);
    const open = css.indexOf('{', at);
    const close = css.indexOf('}', open);
    if (close === -1) throw new Error(`build-css: unterminated rule for "${selector}"`);
    return css
        .slice(open + 1, close)
        .split('\n')
        .map((l) => l.replace(/^ {8}/, '    '))
        .join('\n')
        .replace(/^\n+|\n+$/g, '');
}

const appCss = readFileSync(APP_CSS, 'utf8');
const light = ruleBody(appCss, '.product-shell');
const dark = ruleBody(appCss, '.dark .product-shell');
const button = ruleBody(appCss, ".product-shell [data-slot='button']");

// Tailwind errors on a @source path that does not exist.
if (!existsSync(PREVIEWS)) mkdirSync(PREVIEWS, { recursive: true });

const safelist = readFileSync(join(HERE, 'safelist.css'), 'utf8');

const tokenCount = (light.match(/^\s*--/gm) ?? []).length;

writeFileSync(
    SOURCE,
    `/*
 * GENERATED by .design-sync/build-css.mjs — do not edit, do not commit.
 * Regenerate with: node .design-sync/build-css.mjs
 */

@import './app.css';

/* The preview cards are authored outside the app's own source tree, so
   Tailwind would not otherwise see the classes they use. */
@source '${PREVIEWS}';

${safelist}

/* ──────────────────────────────────────────────────────────────────────────
 * Product palette promoted to the document root.
 *
 * Copied verbatim from \`.product-shell\` in app.css (${tokenCount} declarations).
 * Unlayered and later in source order, so it wins over both the stock \`:root\`
 * block and the layered \`.product-shell\` rule it came from.
 */
:root {
${light}
}

.dark {
${dark}
}

[data-slot='button'] {
${button}
}
`,
    'utf8',
);

console.error(`» wrote ${SOURCE} (${tokenCount} promoted tokens)`);

const cli = join(REPO, '.ds-sync', 'node_modules', '.bin', 'tailwindcss');
execFileSync(cli, ['-i', SOURCE, '-o', OUT, '--cwd', join(REPO, 'app')], {
    stdio: 'inherit',
});

const bytes = readFileSync(OUT).length;
console.error(`» wrote ${OUT} (${(bytes / 1024).toFixed(0)} KB)`);
