import { Link } from '@inertiajs/react';
import { Facts, LegalPage, Section } from '@/components/legal-page';
import type { LegalEntity } from '@/components/legal-page';
import { privacy } from '@/routes/legal';

export default function Terms({
    entity,
    updated,
}: {
    entity: LegalEntity;
    updated: string;
}) {
    return (
        <LegalPage
            title="Terms of Service"
            intro={`The agreement between you and ${entity.name} for the use of ${entity.product}.`}
            updated={updated}
            entity={entity}
        >
            <section>
                <Facts
                    rows={[
                        ['Provider', entity.name],
                        [
                            'Registered office',
                            `${entity.address} (company number ${entity.companyNumber})`,
                        ],
                        ['Service', `${entity.product}, at ${entity.site}`],
                        [
                            'Contact',
                            <a href={`mailto:${entity.email}`}>
                                {entity.email}
                            </a>,
                        ],
                        ['Governing law', entity.jurisdiction],
                    ]}
                />
            </section>

            <Section id="agreement" title="1. This agreement">
                <p>
                    These terms govern your use of {entity.product} (the
                    "Service"), operated by {entity.name}, a company registered
                    in {entity.jurisdiction} under number {entity.companyNumber}
                    , whose registered office is at {entity.address} ("we",
                    "us", "our").
                </p>
                <p>
                    By using the Service you agree to these terms. If you are
                    using it on behalf of an organisation, you confirm you are
                    authorised to accept them for that organisation, and "you"
                    means that organisation.
                </p>
            </Section>

            <Section id="service" title="2. What the Service does">
                <p>
                    {entity.product} is a software platform for organic
                    marketing. It builds a brand brief from material you supply,
                    plans content, drafts articles and social posts, generates
                    images, checks how visible your brand is in search engines
                    and AI assistants, and — where you connect a channel —
                    publishes approved work and collects the replies it
                    receives.
                </p>
                <p>
                    <strong>
                        The Service is software. It is not a marketing agency, a
                        legal or financial adviser, and it does not provide
                        professional advice of any kind.
                    </strong>{' '}
                    What it produces is a draft for you to judge.
                </p>
            </Section>

            <Section id="accounts" title="3. Accounts">
                <p>
                    There is no public sign-up. Accounts are created by us for
                    named people, and an account is personal to the individual
                    it was issued to.
                </p>
                <ul>
                    <li>
                        Keep your credentials secret and do not share a login
                        between people.
                    </li>
                    <li>
                        You are responsible for everything done through your
                        account.
                    </li>
                    <li>
                        Tell us promptly at{' '}
                        <a href={`mailto:${entity.email}`}>{entity.email}</a> if
                        you believe your account has been compromised.
                    </li>
                    <li>You must be at least 18 to use the Service.</li>
                </ul>
            </Section>

            <Section
                id="ai"
                title="4. Automated content, and your responsibility for it"
            >
                <p>
                    Much of what the Service produces is generated by
                    third-party AI models. That has consequences you should
                    treat as certainties rather than risks:
                </p>
                <ul>
                    <li>
                        <strong>Output can be wrong.</strong> Generated text may
                        contain statements that are inaccurate, out of date, or
                        entirely fabricated, including invented sources,
                        statistics, quotations, and citations.
                    </li>
                    <li>
                        <strong>Output is not guaranteed original.</strong> We
                        do not warrant that generated text or imagery is free of
                        third-party rights, and similar output may be generated
                        for other users.
                    </li>
                    <li>
                        <strong>Output is not compliance-checked.</strong> It is
                        not reviewed against advertising rules, sector
                        regulation, or the rules of any platform you publish to.
                    </li>
                </ul>
                <p>
                    The Service is built so that nothing reaches the public
                    without a person approving it, and it will stay that way.
                    You are the publisher of everything you approve, and you are
                    responsible for reviewing it for accuracy, rights, and
                    legality before it goes out. Where you switch on automatic
                    publishing for a connected channel, you accept that
                    responsibility for what that channel publishes.
                </p>
            </Section>

            <Section id="your-content" title="5. Your content">
                <p>
                    You keep ownership of everything you put into the Service —
                    your brand material, your site content, your instructions —
                    and, as between you and us, of the drafts and images the
                    Service produces for you.
                </p>
                <p>
                    You grant us a licence to host, copy, process and transmit
                    that material for the purpose of operating the Service for
                    you, including sending it to the providers listed in our{' '}
                    <Link href={privacy.url()}>privacy policy</Link>. That
                    licence exists so the Service can work and ends when the
                    material is deleted.
                </p>
                <p>
                    You confirm you have the rights to the material you supply,
                    and that our processing of it will not infringe anyone
                    else's rights.
                </p>
            </Section>

            <Section id="connections" title="6. Connected accounts">
                <p>
                    The Service can connect to third-party accounts you control,
                    such as Google Search Console, Google Analytics, and
                    Threads. Those connections are made with your authorisation
                    and can be withdrawn by you at any time, from within the
                    Service or from the provider.
                </p>
                <p>
                    Your use of those platforms remains governed by their own
                    terms. You are responsible for holding the rights to connect
                    an account and for complying with the rules of any platform
                    you publish to. We are not responsible for a third-party
                    platform changing its terms, its API, or its treatment of
                    your account.
                </p>
            </Section>

            <Section id="acceptable-use" title="7. Acceptable use">
                <p>You must not use the Service to:</p>
                <ul>
                    <li>
                        break the law, infringe intellectual property, or breach
                        anyone's privacy;
                    </li>
                    <li>
                        produce or publish material that is deceptive,
                        harassing, defamatory, hateful, or sexual content
                        involving children;
                    </li>
                    <li>
                        impersonate a person or organisation, or misrepresent
                        automated content as the independent work of a named
                        individual where doing so would mislead;
                    </li>
                    <li>
                        generate content at a volume or in a manner intended to
                        manipulate search rankings or platform recommendation
                        systems in breach of those platforms' rules;
                    </li>
                    <li>
                        crawl, audit, or publish to a site or account you do not
                        control or have permission to act for;
                    </li>
                    <li>
                        probe or interfere with the Service's security, evade
                        its rate limits, resell access to it, or use it to build
                        a competing product.
                    </li>
                </ul>
            </Section>

            <Section id="fees" title="8. Fees">
                <p>
                    Where the Service is provided under a paid plan, the fees,
                    the billing period, and what is included are those agreed
                    with you in writing. Fees are stated exclusive of VAT and
                    other taxes, which are added where the law requires.
                </p>
                <p>
                    Some features consume paid capacity from third-party
                    providers — model calls, image generation, and search data.
                    Usage is metered and visible to you inside the Service, and
                    we may apply fair-use limits to protect the Service for
                    everyone.
                </p>
            </Section>

            <Section id="availability" title="9. Availability and support">
                <p>
                    We work to keep the Service available but do not promise it
                    will be uninterrupted or error-free. We may change, suspend
                    or withdraw features, and will give reasonable notice of a
                    material change where we can.
                </p>
                <p>
                    Parts of the Service depend on third parties. If a model
                    provider, a search-data provider, or a publishing platform
                    is unavailable, degraded, or changes its terms, the features
                    that rely on it may be unavailable too.
                </p>
            </Section>

            <Section id="ip" title="10. Our intellectual property">
                <p>
                    The Service itself — its software, design, and documentation
                    — belongs to us and our licensors. Nothing in these terms
                    transfers it to you. You may not copy, decompile, or
                    reverse-engineer it except to the extent the law says you
                    may.
                </p>
                <p>
                    If you send us feedback or suggestions, we may use them
                    without obligation to you.
                </p>
            </Section>

            <Section id="warranties" title="11. Disclaimer">
                <p>
                    Except as these terms expressly say, the Service is provided
                    "as is" and "as available", and we exclude all warranties,
                    conditions and terms implied by statute or common law to the
                    fullest extent the law permits. In particular we do not
                    warrant that the Service will produce any specific marketing
                    result, ranking, traffic level, or visibility in search
                    engines or AI assistants.
                </p>
            </Section>

            <Section id="liability" title="12. Liability">
                <p>
                    Nothing in these terms limits liability for death or
                    personal injury caused by negligence, for fraud or
                    fraudulent misrepresentation, or for anything else that
                    cannot lawfully be limited.
                </p>
                <p>Subject to that, we are not liable for:</p>
                <ul>
                    <li>
                        loss of profit, revenue, business, goodwill, or
                        anticipated savings;
                    </li>
                    <li>
                        loss or corruption of data, beyond restoring from our
                        routine backups;
                    </li>
                    <li>
                        any consequence of content you approved and published,
                        including its accuracy, its rights position, and its
                        treatment by a third-party platform;
                    </li>
                    <li>indirect or consequential loss of any kind.</li>
                </ul>
                <p>
                    Our total liability arising out of or in connection with
                    these terms is limited to the greater of the fees you paid
                    us in the twelve months before the claim arose, or £100.
                </p>
                <p>
                    If you use the Service as a consumer rather than for
                    business purposes, nothing here affects your statutory
                    rights.
                </p>
            </Section>

            <Section id="termination" title="13. Suspension and termination">
                <p>
                    You may stop using the Service at any time and ask us to
                    close your account. We may suspend or close an account that
                    breaches these terms, that creates a security or legal risk,
                    or where required by law — immediately where the breach is
                    serious, and otherwise on reasonable notice.
                </p>
                <p>
                    You can export or ask us for your content before closure. We
                    delete or anonymise data after closure as described in the{' '}
                    <Link href={privacy.url()}>privacy policy</Link>.
                </p>
            </Section>

            <Section id="changes" title="14. Changes to these terms">
                <p>
                    We may update these terms. If a change materially reduces
                    your rights we will tell registered users by email or in the
                    Service before it takes effect. Continuing to use the
                    Service after that means you accept the updated terms; if
                    you do not, stop using it and ask us to close your account.
                </p>
            </Section>

            <Section id="general" title="15. General">
                <p>
                    These terms, together with the{' '}
                    <Link href={privacy.url()}>privacy policy</Link>, are the
                    whole agreement between us about the Service. If a clause is
                    found unenforceable the rest continues to apply. A delay in
                    enforcing a right does not waive it. You may not transfer
                    your rights under these terms without our consent.
                </p>
                <p>
                    These terms and any dispute arising from them are governed
                    by the law of {entity.jurisdiction}, and the courts of{' '}
                    {entity.jurisdiction} have exclusive jurisdiction.
                </p>
            </Section>

            <Section id="contact" title="16. Contact">
                <p>
                    {entity.name}, {entity.address}. Questions about these terms
                    go to <a href={`mailto:${entity.email}`}>{entity.email}</a>.
                </p>
            </Section>
        </LegalPage>
    );
}
