<?php

declare(strict_types=1);

namespace App\Pipelines\Definitions;

use App\Pipelines\Contracts\PipelineDefinition;
use App\Pipelines\Contracts\Step;
use App\Pipelines\Steps\Generation\BuildGeoLayer;
use App\Pipelines\Steps\Generation\CompileBrief;
use App\Pipelines\Steps\Generation\CoverEntities;
use App\Pipelines\Steps\Generation\FactCheck;
use App\Pipelines\Steps\Generation\FinaliseDraft;
use App\Pipelines\Steps\Generation\IllustrateDraft;
use App\Pipelines\Steps\Generation\LinkToSite;
use App\Pipelines\Steps\Generation\VerifyLinks;
use App\Pipelines\Steps\Generation\WriteDraft;
use App\Pipelines\Steps\Generation\WriteOutline;

/**
 * Generation, daily (§4 pipeline 3, §5).
 *
 *                                              ┌─ fact_check ─────┐
 *  compile_brief → write_outline → write_draft ─┼─ build_geo_layer ─┼→ finalise_draft
 *                                              └─ cover_entities ──┘
 *
 * The three-way fan-out is the shape the work actually has: once a body exists,
 * checking its claims, building its schema and measuring its entity coverage
 * are three unrelated questions about the same text. Two of them call a model
 * and go to the expensive queue; the third is a string search and does not.
 *
 * Interlinking on pgvector is absent deliberately — §5's
 * out-of-scope note puts both in phase 8, and this pipeline only leaves the
 * image anchors behind.
 */
class GenerationPipeline implements PipelineDefinition
{
    public static function key(): string
    {
        return 'generation';
    }

    public static function version(): int
    {
        return 1;
    }

    public static function name(): string
    {
        return 'Generation (plan → draft with GEO)';
    }

    /** @return list<class-string<Step>> */
    public function steps(): array
    {
        return [
            CompileBrief::class,
            WriteOutline::class,
            WriteDraft::class,
            VerifyLinks::class,
            LinkToSite::class,
            FactCheck::class,
            BuildGeoLayer::class,
            CoverEntities::class,
            FinaliseDraft::class,
            IllustrateDraft::class,
        ];
    }

    /** @return array<string, mixed> */
    public function inputRules(): array
    {
        return [
            // Normally carried on the run itself; accepted here so a single
            // unit can be regenerated by hand without inventing a run shape.
            'content_item_id' => ['sometimes', 'string'],
        ];
    }
}
